version: '3.0'
services:
  rick-and-morty-web:
    container_name: rick-and-morty-web
    build: 
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ./.docker/entrypoint.sh
    environment:
      - "TZ=America/Sao_Paulo"
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - .:/home/node/app
